name: Build & Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI/CD
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install & Build
        run: |
          npm ci
          npm run generate

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

      - name: Add host key
        run: ssh-keyscan -p ${{ secrets.DEPLOY_SERVER_PORT }} ${{ secrets.DEPLOY_TO }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.DEPLOY_SERVER_PORT }}" \
            .output/public/ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_TO }}:${{ secrets.DEPLOY_TARGET }}
